#!/usr/bin/env python3
"""
plot_init_sensitivity_signature.py
====================================
Two complementary figures that show **each init type has a distinct
behavioral signature** across state conditions.

Figure 1 — Sensitivity profile
    For each motivation (4 panels), one line per init showing
    median P(sel=M | mask) across all 6 state masks.
    "Shape" (flat vs peaked, child-biased vs mother-biased) is the signature.

Figure 2 — Init-contrast heatmap
    For each (motivation, mask) cell:
        contrast = median_anti − median_pro
    Diverging colormap shows which combinations have the largest gap
    between the most extreme init types. One panel per plasticity.

Figure 3 — 2-D behavioral scatter
    Each genome (plasticity × init × seed) is one dot in the plane
    (P(Care | child_hungry), P(Forage | child_hungry)).
    Colored by init type. Shows whether the three types occupy
    distinct regions of behavioral space, not just different averages.

Usage
-----
From extended conditional_metrics_single.csv (generated by
plot_runlog_conditional_behavior.py --extended):

    python3 plot_init_sensitivity_signature.py \\
        --csv FinalGenomeRollouts_normal_seen/figures_conditional_extended/conditional_metrics_single.csv \\
        --out-dir paper_figures_init_signature

Or pass multiple CSVs to overlay worlds (profiles only):

    python3 plot_init_sensitivity_signature.py \\
        --csv normal=FinalGenomeRollouts_normal_seen/.../conditional_metrics_single.csv \\
        --csv unseen_hard=FinalGenomeRollouts_unseen_hard/.../conditional_metrics_single.csv \\
        --out-dir paper_figures_init_signature
"""

from __future__ import annotations

import argparse
import os
import sys

import numpy as np

try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.patheffects as pe
    import pandas as pd
except ImportError as e:
    raise SystemExit(f"Requires pandas+matplotlib: {e}") from e

# ── colour scheme ──────────────────────────────────────────────────────────────
INIT_ORDER = ["anti_maternal", "random_uniform", "pro_maternal"]
INIT_LABELS = {"anti_maternal": "anti-maternal", "random_uniform": "random", "pro_maternal": "pro-maternal"}
INIT_COLORS = {"anti_maternal": "#c0392b", "random_uniform": "#2980b9", "pro_maternal": "#27ae60"}
PLAST_ORDER = ["E2", "P1", "P2"]

CONDITION_KEYS = [
    "child_hungry",
    "child_cold",
    "child_injured",
    "mother_fear_hi",
    "mother_energy_lo",
    "mother_stress_hi",
]
CONDITION_LABELS = ["Child\nhungry", "Child\ncold", "Child\ninjured", "Mother\nfear↑", "Mother\nenergy↓", "Mother\nstress↑"]

MOTIVATIONS = ("Forage", "Care", "Self", "Protect")
MOT_COLORS = {"Forage": "#4C78A8", "Care": "#F58518", "Self": "#54A24B", "Protect": "#B279A2"}

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
    "font.size": 10,
    "axes.titlesize": 11,
    "axes.labelsize": 10,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.linewidth": 0.9,
    "figure.facecolor": "white",
    "axes.facecolor": "white",
    "savefig.facecolor": "white",
})


# ── data helpers ───────────────────────────────────────────────────────────────

def _psel_col(mot: str, ck: str) -> str:
    return f"P_sel_{mot}_given_{ck}"


def _load_and_aggregate(csv_path: str) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    pcols = [_psel_col(m, ck) for m in MOTIVATIONS for ck in CONDITION_KEYS]
    missing = [c for c in pcols if c not in df.columns]
    if missing:
        raise SystemExit(f"{csv_path}: missing extended columns {missing[:3]}… (re-run with --extended)")
    for c in pcols:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    # per-genome mean (collapse rollout repetitions within a seed)
    return df.groupby(["plasticity", "init", "evolve_seed"], as_index=False)[pcols].mean()


def _median_profile(pg: pd.DataFrame, *, mot: str, plast: str, init: str) -> np.ndarray:
    sub = pg[(pg["plasticity"] == plast) & (pg["init"] == init)]
    return np.array([
        float(sub[_psel_col(mot, ck)].median()) if not sub.empty else np.nan
        for ck in CONDITION_KEYS
    ], dtype=float)


def _iqr_profile(pg: pd.DataFrame, *, mot: str, plast: str, init: str) -> tuple[np.ndarray, np.ndarray]:
    sub = pg[(pg["plasticity"] == plast) & (pg["init"] == init)]
    lo = np.array([float(sub[_psel_col(mot, ck)].quantile(0.25)) if not sub.empty else np.nan for ck in CONDITION_KEYS])
    hi = np.array([float(sub[_psel_col(mot, ck)].quantile(0.75)) if not sub.empty else np.nan for ck in CONDITION_KEYS])
    return lo, hi


# ── Figure 1: sensitivity profile ─────────────────────────────────────────────

def plot_sensitivity_profile(
    datasets: dict[str, pd.DataFrame],   # label → per-genome df
    *,
    plast: str = "E2",
    out_png: str,
    title_suffix: str = "",
) -> None:
    """
    4 rows (motivations) × 1 col (or 3 cols if multiple worlds).
    Each row: median ± IQR line per init across 6 state masks.
    """
    n_worlds = len(datasets)
    n_mot = len(MOTIVATIONS)
    fig, axes = plt.subplots(n_mot, max(n_worlds, 1), figsize=(max(n_worlds, 1) * 5.5, n_mot * 2.5 + 0.5),
                             sharey="row", sharex=True, layout="constrained")
    if n_worlds == 1:
        axes = axes[:, np.newaxis]

    x = np.arange(len(CONDITION_KEYS), dtype=float)

    for mi, mot in enumerate(MOTIVATIONS):
        for wi, (wlabel, pg) in enumerate(datasets.items()):
            ax = axes[mi, wi]
            ax.grid(False)
            for init in INIT_ORDER:
                med = _median_profile(pg, mot=mot, plast=plast, init=init)
                lo, hi = _iqr_profile(pg, mot=mot, plast=plast, init=init)
                col = INIT_COLORS[init]
                ax.fill_between(x, lo, hi, color=col, alpha=0.14, linewidth=0)
                ax.plot(x, med, "-o", color=col, linewidth=2.0, markersize=5,
                        label=INIT_LABELS[init] if mi == 0 else None)
            ax.set_ylim(-0.04, 1.04)
            ax.axhline(0, color="0.80", linewidth=0.5)
            if wi == 0:
                ax.set_ylabel(f"P({mot} | mask)", fontsize=9)
            if mi == n_mot - 1:
                ax.set_xticks(x)
                ax.set_xticklabels(CONDITION_LABELS, fontsize=7.5)
            if mi == 0:
                ax.set_title(wlabel, fontsize=10)

    # shared legend at top right
    handles = [plt.Line2D([0], [0], color=INIT_COLORS[i], linewidth=2) for i in INIT_ORDER]
    labels_ = [INIT_LABELS[i] for i in INIT_ORDER]
    fig.legend(handles, labels_, loc="lower center", ncol=3, fontsize=9, frameon=False,
               bbox_to_anchor=(0.5, -0.02), title="init type")

    fig.suptitle(
        f"Init sensitivity profiles — {plast}{(' — ' + title_suffix) if title_suffix else ''}\n"
        "rows = motivation, cols = world; median ± IQR across genomes",
        fontsize=11,
    )
    fig.savefig(out_png, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print("[ok] wrote", out_png)


# ── Figure 2: init-contrast heatmap ───────────────────────────────────────────

def plot_contrast_heatmap(
    pg: pd.DataFrame,
    *,
    init_a: str = "anti_maternal",
    init_b: str = "pro_maternal",
    out_png: str,
    title_suffix: str = "",
) -> None:
    """
    3 panels (one per plasticity).
    Each panel: 4 motivations × 6 masks.
    Cell value = median_{init_a} − median_{init_b}  (across genomes in that plasticity).
    """
    fig, axes = plt.subplots(1, 3, figsize=(13.0, 3.8), layout="constrained")
    ims = []
    for ax, plast in zip(axes, PLAST_ORDER):
        ax.grid(False)
        mat = np.full((len(MOTIVATIONS), len(CONDITION_KEYS)), np.nan, dtype=float)
        for mi, mot in enumerate(MOTIVATIONS):
            for ci, ck in enumerate(CONDITION_KEYS):
                col = _psel_col(mot, ck)
                va = pg[(pg["plasticity"] == plast) & (pg["init"] == init_a)][col].dropna()
                vb = pg[(pg["plasticity"] == plast) & (pg["init"] == init_b)][col].dropna()
                if va.size and vb.size:
                    mat[mi, ci] = float(np.median(va)) - float(np.median(vb))
        finite = mat[np.isfinite(mat)]
        lim = float(np.max(np.abs(finite))) if finite.size else 0.3
        lim = max(lim, 0.05)
        im = ax.imshow(mat, aspect="auto", cmap="RdBu_r", vmin=-lim, vmax=lim)
        ims.append(im)
        ax.set_xticks(np.arange(len(CONDITION_KEYS)))
        ax.set_xticklabels(CONDITION_LABELS, fontsize=8)
        ax.set_yticks(np.arange(len(MOTIVATIONS)))
        ax.set_yticklabels(list(MOTIVATIONS))
        ax.set_title(plast, fontsize=11)
        # annotate cells
        for mi in range(mat.shape[0]):
            for ci in range(mat.shape[1]):
                v = mat[mi, ci]
                if np.isfinite(v):
                    txt = ax.text(ci, mi, f"{v:+.2f}", ha="center", va="center", fontsize=6.5,
                                  color="white" if abs(v) > lim * 0.6 else "black")
                    txt.set_path_effects([pe.withStroke(linewidth=1.0, foreground="black" if abs(v) > lim * 0.6 else "white")])

        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.03,
                     label=f"median\n{INIT_LABELS[init_a]} − {INIT_LABELS[init_b]}")

    fig.suptitle(
        f"Init contrast: {INIT_LABELS[init_a]} minus {INIT_LABELS[init_b]}{(' — ' + title_suffix) if title_suffix else ''}\n"
        "cell = median ΔP  (rows=motivation, cols=state mask)",
        fontsize=11,
    )
    fig.savefig(out_png, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print("[ok] wrote", out_png)


# ── Figure 3: 2-D behavioral space scatter ────────────────────────────────────

def plot_behavioral_scatter(
    pg: pd.DataFrame,
    *,
    x_col: str = "P_sel_Care_given_child_hungry",
    y_col: str = "P_sel_Forage_given_child_hungry",
    x_label: str = "P(Care | child hungry)",
    y_label: str = "P(Forage | child hungry)",
    out_png: str,
    title_suffix: str = "",
) -> None:
    """
    3 panels (plasticity). Each genome = one dot, colored by init.
    Shows whether init types occupy distinct behavioral regions.
    """
    fig, axes = plt.subplots(1, 3, figsize=(13.5, 4.2), sharey=True, sharex=True, layout="constrained")
    rng = np.random.default_rng(0)
    for ax, plast in zip(axes, PLAST_ORDER):
        ax.grid(True, color="0.92", linewidth=0.7)
        sub = pg[pg["plasticity"] == plast]
        for init in INIT_ORDER:
            s = sub[sub["init"] == init]
            if s.empty:
                continue
            xv = pd.to_numeric(s[x_col], errors="coerce").to_numpy(dtype=float)
            yv = pd.to_numeric(s[y_col], errors="coerce").to_numpy(dtype=float)
            ok = np.isfinite(xv) & np.isfinite(yv)
            xv, yv = xv[ok], yv[ok]
            # jitter tiny amount so overlapping genomes separate
            xv += rng.normal(0, 0.008, size=xv.shape)
            yv += rng.normal(0, 0.008, size=yv.shape)
            ax.scatter(xv, yv, c=INIT_COLORS[init], s=22, alpha=0.55, edgecolors="none",
                       label=INIT_LABELS[init])
            # centroid marker
            if ok.sum():
                ax.scatter([float(np.median(xv))], [float(np.median(yv))],
                           c=INIT_COLORS[init], s=90, marker="D", edgecolors="white",
                           linewidth=0.8, zorder=5)
        ax.axhline(0.33, color="0.65", linewidth=0.6, linestyle=":")
        ax.axvline(0.33, color="0.65", linewidth=0.6, linestyle=":")
        ax.set_title(plast, fontsize=11)
        ax.set_xlabel(x_label, fontsize=9)
        if ax == axes[0]:
            ax.set_ylabel(y_label, fontsize=9)

    handles = [plt.Line2D([0], [0], marker="o", color="w", markerfacecolor=INIT_COLORS[i],
                          markersize=7) for i in INIT_ORDER]
    fig.legend(handles, [INIT_LABELS[i] for i in INIT_ORDER],
               loc="lower center", ncol=3, fontsize=9, frameon=False,
               bbox_to_anchor=(0.5, -0.04), title="init type (◆ = median)")
    fig.suptitle(
        f"Behavioral space: {x_label}  vs  {y_label}{(' — ' + title_suffix) if title_suffix else ''}\n"
        "each dot = one evolved genome; ◆ = median per init type",
        fontsize=10,
    )
    fig.savefig(out_png, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print("[ok] wrote", out_png)


# ── main ───────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument(
        "--csv",
        action="append",
        default=[],
        metavar="[label=]path",
        help=(
            "Extended conditional_metrics_single.csv. Repeatable. "
            "May be prefixed 'label=' for multi-world profile. "
            "Without prefix the basename is used."
        ),
    )
    ap.add_argument("--plasticity", default="E2", help="Plasticity to use for profile plot (default E2).")
    ap.add_argument("--out-dir", required=True, help="Output directory.")
    ap.add_argument("--title", default="", help="Extra label appended to figure titles.")
    ap.add_argument(
        "--contrast-a", default="anti_maternal",
        choices=["anti_maternal", "random_uniform", "pro_maternal"],
        help="Numerator init for contrast heatmap.",
    )
    ap.add_argument(
        "--contrast-b", default="pro_maternal",
        choices=["anti_maternal", "random_uniform", "pro_maternal"],
        help="Denominator init for contrast heatmap.",
    )
    args = ap.parse_args()

    if not args.csv:
        print("[error] provide at least one --csv path", file=sys.stderr)
        return 2

    os.makedirs(args.out_dir, exist_ok=True)

    datasets: dict[str, pd.DataFrame] = {}
    for spec in args.csv:
        if "=" in spec:
            label, raw_paths = spec.split("=", 1)
        else:
            raw_paths = spec
            label = os.path.basename(os.path.dirname(os.path.abspath(spec)))
        label = label.strip()
        # support comma-separated paths under the same label (merged worlds / split seeds)
        paths = [p.strip() for p in raw_paths.split(",")]
        parts = [_load_and_aggregate(p) for p in paths]
        pg = pd.concat(parts, ignore_index=True) if len(parts) > 1 else parts[0]
        datasets[label] = pg

    # Figure 1: sensitivity profile (one per plasticity)
    for plast in PLAST_ORDER:
        plot_sensitivity_profile(
            datasets,
            plast=plast,
            out_png=os.path.join(args.out_dir, f"sensitivity_profile_{plast}.png"),
            title_suffix=args.title,
        )

    # Figures 2 and 3 use only the first CSV (single world)
    first_label, first_pg = next(iter(datasets.items()))

    plot_contrast_heatmap(
        first_pg,
        init_a=args.contrast_a,
        init_b=args.contrast_b,
        out_png=os.path.join(args.out_dir, "contrast_heatmap.png"),
        title_suffix=f"{first_label}{(' — ' + args.title) if args.title else ''}",
    )

    plot_behavioral_scatter(
        first_pg,
        out_png=os.path.join(args.out_dir, "behavioral_scatter_care_forage.png"),
        title_suffix=f"{first_label}{(' — ' + args.title) if args.title else ''}",
    )

    # also scatter for fear condition
    plot_behavioral_scatter(
        first_pg,
        x_col="P_sel_Care_given_mother_fear_hi",
        y_col="P_sel_Protect_given_mother_fear_hi",
        x_label="P(Care | mother fear↑)",
        y_label="P(Protect | mother fear↑)",
        out_png=os.path.join(args.out_dir, "behavioral_scatter_care_protect_fear.png"),
        title_suffix=f"{first_label}{(' — ' + args.title) if args.title else ''}",
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
